name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish the module"
        required: false
        default: true
        type: boolean

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      packages: write
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: canary

      - id: check
        name: run checks
        run: |
          deno lint
          deno fmt --check
          deno test -A --no-check=remote --permit-no-files
          deno doc --lint mod.ts

      - id: publish
        if: |
          steps.check.outcome == 'success' && (
            (
              github.event_name == 'workflow_dispatch' &&
              github.event.inputs.publish == 'true'
            ) || (
              github.event_name == 'push' &&
              startsWith(github.ref, 'refs/tags/')
            )
          )
        name: publish to jsr
        run: deno publish --dry-run --allow-dirty && deno publish --allow-dirty
